-- 1. PASTIKAN TABEL POSTS ADA & LENGKAP
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  user_id uuid references auth.users not null,
  content text,
  image_url text,
  likes int default 0,
  
  -- KOLOM LOGASI (PENTING BUAT FILTER)
  country_id bigint references public.countries(id),
  diocese_id bigint references public.dioceses(id),
  parish_id bigint references public.parishes(id)
);

-- 2. ENABLE RLS (Agar aman)
alter table public.posts enable row level security;

-- 3. POLICIES
-- Semua orang boleh baca
create policy "Public read posts" 
on public.posts for select using (true);

-- User login boleh posting
create policy "Authenticated insert posts" 
on public.posts for insert 
with check (auth.uid() = user_id);

-- User hanya boleh edit/hapus post sendiri
create policy "Owner update posts" 
on public.posts for update using (auth.uid() = user_id);

create policy "Owner delete posts" 
on public.posts for delete using (auth.uid() = user_id);
