-- ==============================================================================
-- MIGRATION SCRIPT: SOCIAL FEATURES & PROFILE FIXES
-- ==============================================================================
-- Author: Antigravity
-- Description: Updates 'posts' table and creates 'user_follows', 'user_reports'.
--              Includes RLS policies and helper functions.

-- ------------------------------------------------------------------------------
-- 1. UPDATE 'posts' TABLE
-- ------------------------------------------------------------------------------
-- Ensure 'posts' table has the required columns.
-- Using "IF NOT EXISTS" to prevent errors if running multiple times.

DO $$ 
BEGIN
    -- Add 'caption' column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'caption') THEN
        ALTER TABLE public.posts ADD COLUMN caption text;
    END IF;

    -- Add 'content_url' column (for images/videos)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'content_url') THEN
        ALTER TABLE public.posts ADD COLUMN content_url text;
    END IF;

    -- Add 'type' column (image/text/video)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'type') THEN
        ALTER TABLE public.posts ADD COLUMN type text DEFAULT 'text';
    END IF;

    -- Ensure 'created_at' exists (it usually does, but safe check)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'created_at') THEN
        ALTER TABLE public.posts ADD COLUMN created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL;
    END IF;
END $$;

-- Enable RLS on 'posts' (idempotent)
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------------------
-- 2. CREATE 'user_follows' TABLE (Social Graph)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_follows (
    follower_id UUID REFERENCES auth.users(id) NOT NULL,
    following_id UUID REFERENCES auth.users(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (follower_id, following_id), -- Composite PK prevents duplicate follows
    CONSTRAINT no_self_follow CHECK (follower_id <> following_id)
);

-- Enable RLS
ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;

-- RLS Policies for 'user_follows'

-- 1. Insert: Authenticated users can follow others
DROP POLICY IF EXISTS "Users can follow others" ON public.user_follows;
CREATE POLICY "Users can follow others" 
ON public.user_follows 
FOR INSERT 
WITH CHECK (auth.uid() = follower_id);

-- 2. Delete: Authenticated users can unfollow
DROP POLICY IF EXISTS "Users can unfollow" ON public.user_follows;
CREATE POLICY "Users can unfollow" 
ON public.user_follows 
FOR DELETE 
USING (auth.uid() = follower_id);

-- 3. Select: Anyone can see who follows whom (for counts, lists)
DROP POLICY IF EXISTS "Public read follows" ON public.user_follows;
CREATE POLICY "Public read follows" 
ON public.user_follows 
FOR SELECT 
USING (true);


-- ------------------------------------------------------------------------------
-- 3. CREATE 'user_reports' TABLE (Moderation)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES auth.users(id) NOT NULL,
    reported_user_id UUID REFERENCES auth.users(id) NOT NULL,
    reason TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved', 'dismissed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.user_reports ENABLE ROW LEVEL SECURITY;

-- RLS Policies for 'user_reports'

-- 1. Insert: Authenticated users can submit reports
DROP POLICY IF EXISTS "Users can submit reports" ON public.user_reports;
CREATE POLICY "Users can submit reports" 
ON public.user_reports 
FOR INSERT 
WITH CHECK (auth.uid() = reporter_id);

-- 2. Select: Only Admins or the Reporter can see. 
--    (Adjust logic if you have a specific 'admin' role column or table)
--    For safety, let's allow reporters to see their own reports.
DROP POLICY IF EXISTS "Reporters can view own reports" ON public.user_reports;
CREATE POLICY "Reporters can view own reports" 
ON public.user_reports 
FOR SELECT 
USING (auth.uid() = reporter_id);

-- NOTE: Admin access is usually handled by Service Role key in backend or specific RLS if 'is_admin' column exists.


-- ------------------------------------------------------------------------------
-- 4. PROFILE STATISTICS FUNCTION
-- ------------------------------------------------------------------------------

-- Function to get follower, following, and post counts in one request
CREATE OR REPLACE FUNCTION get_profile_stats(target_user_id UUID)
RETURNS TABLE (
    followers_count BIGINT,
    following_count BIGINT,
    posts_count BIGINT
) 
LANGUAGE plpgsql
SECURITY DEFINER -- Runs with elevated privileges to count efficiently
AS $$
BEGIN
    RETURN QUERY 
    SELECT 
        (SELECT count(*) FROM public.user_follows WHERE following_id = target_user_id) as followers_count,
        (SELECT count(*) FROM public.user_follows WHERE follower_id = target_user_id) as following_count,
        (SELECT count(*) FROM public.posts WHERE user_id = target_user_id) as posts_count;
END;
$$;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION get_profile_stats(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION get_profile_stats(UUID) TO service_role;

-- ==============================================================================
-- END OF SCRIPT
-- ==============================================================================
