-- 1. Buat Tabel AJAKAN MISA
create table public.mass_invitations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  user_id uuid references auth.users not null, -- Link ke User pembuat
  creator_name text, -- Kita simpan nama user di sini agar loading cepat
  
  parish_id bigint references public.parishes(id) not null, -- Link ke Paroki (Wajib Valid)
  
  event_time timestamp with time zone not null, -- Waktu Misa
  notes text, -- Catatan (misal: "Kumpul di depan patung Bunda Maria")
  
  attendees_count int default 1 -- Jumlah yang ikut (awal 1 orang yaitu pembuat)
);

-- 2. Aktifkan Keamanan (RLS)
alter table public.mass_invitations enable row level security;

-- Policy: Semua orang boleh melihat ajakan
create policy "Public read invitations" 
on public.mass_invitations for select using (true);

-- Policy: User login boleh membuat ajakan
create policy "Authenticated users can create" 
on public.mass_invitations for insert 
with check (auth.uid() = user_id);
